import { useEffect, useState } from "react";
type Org={id:number;name:string;role:string};
type Course={id:number;name:string;code:string;level:string};
type Period={id:number;name:string;year:number};
type Assessment={id:number;title:string;category:string;courseId:number;periodId:number;maxMarks:number;weight:number;instructions:string|null};
type Settings={institutionType:string;framework:string;academicYear:number};
type Grade={courseName:string;periodName:string;percentage:number;assessments:number;provisional:boolean;weightIncluded:number};
type Leader={rank:number;name:string;percentage:number;assessments:number;provisional:boolean};
type Report={results:Grade[];assessments:{courseName:string;title:string;periodName:string;marks:number;maxMarks:number;percentage:number}[]};
type AssignedExam={id:number;examId:number;groupId:number;organizationId:number};
type PendingExam={linkId:number;assessmentId:number;assessmentTitle:string;learnerId:string;attemptId:number;score:number;awardedMarks:number;maxMarks:number;reviewRequired:number;reviewed:boolean};
type StaffReport={averageScore:number|null;resultCount:number;results:(Grade&{learnerId:string})[]};
async function api<T>(path:string,method="GET",body?:object):Promise<T>{
 const r=await fetch("/api"+path,{method,credentials:"include",headers:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});
 if(!r.ok){const e=await r.json().catch(()=>({}));throw Error(e.error||"Request failed");}return r.json() as Promise<T>;
}
export default function AcademicsPage(){
 const [orgs,setOrgs]=useState<Org[]>([]),[org,setOrg]=useState(""),[settings,setSettings]=useState<Settings|null>(null);
 const [courses,setCourses]=useState<Course[]>([]),[periods,setPeriods]=useState<Period[]>([]),[assessments,setAssessments]=useState<Assessment[]>([]);
 const [report,setReport]=useState<Report|null>(null),[staffReport,setStaffReport]=useState<StaffReport|null>(null),[leaders,setLeaders]=useState<Leader[]>([]);
 const [linkedAssignments,setLinkedAssignments]=useState<AssignedExam[]>([]),[pending,setPending]=useState<PendingExam[]>([]);
 const [linkAssessment,setLinkAssessment]=useState(""),[linkAssignment,setLinkAssignment]=useState(""),[selectedAttempt,setSelectedAttempt]=useState(""),[approvedMarks,setApprovedMarks]=useState(0),[reviewReason,setReviewReason]=useState(""),[publishApproved,setPublishApproved]=useState(true);
 const [error,setError]=useState(""),[working,setWorking]=useState(false);
 const [framework,setFramework]=useState("NSC"),[institutionType,setType]=useState("school"),[academicYear,setYear]=useState(new Date().getFullYear());
 const [courseName,setCourseName]=useState(""),[code,setCode]=useState(""),[level,setLevel]=useState("Grade 12"),[periodName,setPeriodName]=useState("Term 1");
 const [courseId,setCourseId]=useState(""),[periodId,setPeriodId]=useState(""),[title,setTitle]=useState(""),[category,setCategory]=useState("assignment"),[maxMarks,setMaxMarks]=useState(100),[weight,setWeight]=useState(20),[instructions,setInstructions]=useState("");
 const [enrollCourse,setEnrollCourse]=useState(""),[enrollUser,setEnrollUser]=useState("");
 const [staffEmail,setStaffEmail]=useState(""),[staffCourse,setStaffCourse]=useState(""),[staffAssignments,setStaffAssignments]=useState<{courseId:number;userId:string}[]>([]);
 const [studentId,setStudentId]=useState(""),[gradeAssessment,setGradeAssessment]=useState(""),[score,setScore]=useState(0),[reason,setReason]=useState(""),[publish,setPublish]=useState(false);
 const selected=orgs.find(o=>String(o.id)===org),staff=!!selected&&["owner","admin","teacher","assessor"].includes(selected.role),manager=!!selected&&["owner","admin"].includes(selected.role);
 useEffect(()=>{api<Org[]>("/organizations").then(x=>{setOrgs(x);if(x.length)setOrg(String(x[0].id))}).catch(e=>setError(e.message))},[]);
 async function reload(){
 if(!org)return;
 const [academic,r,assess]=await Promise.all([api<{settings:Settings|null;courses:Course[];periods:Period[]}>("/organizations/"+org+"/academic"),api<Report>("/organizations/"+org+"/academic/my-report"),api<Assessment[]>("/organizations/"+org+"/academic/assessments")]);
 setSettings(academic.settings);setCourses(academic.courses);setPeriods(academic.periods);setAssessments(assess);setReport(r);
 if(academic.settings){setType(academic.settings.institutionType);setFramework(academic.settings.framework);setYear(academic.settings.academicYear)}
 if(manager) setStaffAssignments(await api<{courseId:number;userId:string}[]>("/organizations/"+org+"/academic/course-staff"));
 if(staff){const s=await api<StaffReport>("/organizations/"+org+"/academic/reports");setStaffReport(s);const [assign,queue]=await Promise.all([api<AssignedExam[]>("/organizations/"+org+"/assignments"),api<PendingExam[]>("/organizations/"+org+"/academic/pending-exams")]);setLinkedAssignments(assign);setPending(queue)}
 }
 useEffect(()=>{setError("");setLeaders([]);setStaffReport(null);setReport(null);reload().catch(e=>setError(e.message))},[org]);
 async function action(fn:()=>Promise<unknown>){setWorking(true);setError("");try{await fn();await reload()}catch(e){setError(e instanceof Error?e.message:"Request failed")}finally{setWorking(false)}}
 const field="rounded-md border bg-background px-3 py-2 text-sm";
 const button="rounded-md bg-primary px-4 py-2 text-sm text-primary-foreground disabled:opacity-50";
 const card="rounded-xl border bg-card p-5 space-y-4";
 return <section className="mx-auto max-w-6xl space-y-6 pb-16">
 <header><p className="text-sm uppercase tracking-widest text-muted-foreground">Academic performance</p><h1 className="text-3xl font-semibold">School & university centre</h1><p className="text-muted-foreground">Terms, subjects, assignments, assessments, report cards and progression. Only published marks contribute to results.</p></header>
 {error&&<div role="alert" className="rounded-lg border border-destructive p-3 text-sm">{error}</div>}
 <label className="block text-sm">Institution <select className={field+" ml-2"} value={org} onChange={e=>setOrg(e.target.value)}><option value="">Choose an organization</option>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>
 {!org?<p>Create a school or university under Organizations first. Independent learners can still use Study materials and Written exams.</p>:<>
 {manager&&<section className={card}><h2 className="text-lg font-semibold">Institution setup</h2><div className="flex flex-wrap gap-2"><select aria-label="Institution type" className={field} value={institutionType} onChange={e=>{setType(e.target.value);setFramework(e.target.value==="university"?"UNIVERSITY":"NSC")}}><option value="school">School</option><option value="university">University</option></select><select aria-label="Assessment framework" className={field} value={framework} onChange={e=>setFramework(e.target.value)}>{(institutionType==="school"?["NSC","IEB","CUSTOM"]:["UNIVERSITY","CUSTOM"]).map(x=><option key={x}>{x}</option>)}</select><input aria-label="Academic year" type="number" className={field+" w-28"} value={academicYear} onChange={e=>setYear(Number(e.target.value))}/><button disabled={working} className={button} onClick={()=>action(()=>api("/organizations/"+org+"/academic","PUT",{institutionType,framework,academicYear}))}>Save institution setup</button></div><p className="text-sm text-muted-foreground">Framework labels are for organisation reporting; subject-specific regulatory rules must be reviewed before official results are issued.</p></section>}
 <div className="grid gap-4 md:grid-cols-2"><section className={card}><h2 className="text-lg font-semibold">Subjects & modules</h2>{courses.map(c=><p className="text-sm" key={c.id}>{c.code} · {c.name} <span className="text-muted-foreground">({c.level})</span></p>)}{manager&&<div className="flex flex-wrap gap-2"><input aria-label="Course name" placeholder="Mathematics" className={field} value={courseName} onChange={e=>setCourseName(e.target.value)}/><input aria-label="Course code" placeholder="MATH" className={field+" w-24"} value={code} onChange={e=>setCode(e.target.value)}/><input aria-label="Grade or level" placeholder="Grade 12" className={field} value={level} onChange={e=>setLevel(e.target.value)}/><button disabled={working} className={button} onClick={()=>action(()=>api("/organizations/"+org+"/academic/courses","POST",{name:courseName,code,level}))}>Add</button></div>}</section>
 <section className={card}><h2 className="text-lg font-semibold">Terms & semesters</h2>{periods.map(p=><p className="text-sm" key={p.id}>{p.name} · {p.year}</p>)}{manager&&<div className="flex gap-2"><input aria-label="Period name" className={field} placeholder="Term 1 / Semester 1" value={periodName} onChange={e=>setPeriodName(e.target.value)}/><button disabled={working} className={button} onClick={()=>action(()=>api("/organizations/"+org+"/academic/periods","POST",{name:periodName,year:academicYear}))}>Add period</button></div>}</section></div>
 {staff&&<section className={card}><h2 className="text-lg font-semibold">Create an assignment, test or exam</h2><div className="grid gap-3 sm:grid-cols-3"><select aria-label="Assessment course" className={field} value={courseId} onChange={e=>setCourseId(e.target.value)}><option value="">Subject / module</option>{courses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select aria-label="Assessment term" className={field} value={periodId} onChange={e=>setPeriodId(e.target.value)}><option value="">Term / semester</option>{periods.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select aria-label="Assessment category" className={field} value={category} onChange={e=>setCategory(e.target.value)}>{["assignment","test","exam","practical","oral","project"].map(x=><option key={x}>{x}</option>)}</select><input className={field} aria-label="Assessment title" placeholder="Term assessment" value={title} onChange={e=>setTitle(e.target.value)}/><label className="text-sm">Maximum marks<input className={field+" block w-full"} type="number" min="1" value={maxMarks} onChange={e=>setMaxMarks(Number(e.target.value))}/></label><label className="text-sm">Relative weight (%)<input className={field+" block w-full"} type="number" min="1" max="100" value={weight} onChange={e=>setWeight(Number(e.target.value))}/></label></div><textarea className={field+" w-full"} aria-label="Assessment instructions" rows={3} placeholder="Assignment instructions, submission information…" value={instructions} onChange={e=>setInstructions(e.target.value)}/><button disabled={working||!courseId||!periodId||!title} className={button} onClick={()=>action(()=>api("/organizations/"+org+"/academic/assessments","POST",{courseId:Number(courseId),periodId:Number(periodId),title,category,maxMarks,weight,instructions}))}>Create assessment</button><p className="text-xs text-muted-foreground">This creates a weighted gradebook item and assignment instructions. Online answer submissions for these items are a separate integration.</p></section>}
 {manager&&<section className={card}><h2 className="text-lg font-semibold">Enrol a learner in a subject/module</h2><p className="text-sm text-muted-foreground">The learner must already belong to this institution. Their user ID is available in Organizations → Members.</p><div className="flex flex-wrap gap-2"><select aria-label="Course to enroll" className={field} value={enrollCourse} onChange={e=>setEnrollCourse(e.target.value)}><option value="">Subject / module</option>{courses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input aria-label="Learner ID to enroll" className={field} placeholder="Learner user ID" value={enrollUser} onChange={e=>setEnrollUser(e.target.value)}/><button className={button} disabled={working||!enrollCourse||!enrollUser} onClick={()=>action(()=>api(`/organizations/${org}/academic/courses/${enrollCourse}/enroll`,"POST",{userId:enrollUser}))}>Enrol learner</button></div></section>}
 {manager&&<section className={card}><h2 className="text-lg font-semibold">Assign teachers and assessors to subjects</h2><p className="text-sm text-muted-foreground">Teachers can grade and view results only for courses explicitly assigned to them. The staff member must already belong to this organisation.</p><div className="flex flex-wrap gap-2"><select className={field} aria-label="Subject for teaching responsibility" value={staffCourse} onChange={e=>setStaffCourse(e.target.value)}><option value="">Choose subject</option>{courses.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input className={field} type="email" aria-label="Staff account email" placeholder="teacher@school.org" value={staffEmail} onChange={e=>setStaffEmail(e.target.value)}/><button className={button} disabled={working||!staffCourse||!staffEmail} onClick={()=>action(()=>api("/organizations/"+org+"/academic/course-staff","POST",{courseId:Number(staffCourse),email:staffEmail}))}>Assign staff member</button></div>{staffAssignments.map((a,i)=><p key={i} className="border-b py-2 text-sm">{courses.find(c=>c.id===a.courseId)?.name??"Course"} · {a.userId}</p>)}</section>}
 <section className={card}><h2 className="text-lg font-semibold">Assessment register</h2>{assessments.length===0?<p className="text-sm text-muted-foreground">No assessments yet.</p>:<div className="space-y-2">{assessments.map(a=><div key={a.id} className="flex flex-wrap justify-between gap-2 border-b pb-2 text-sm"><span>{a.title} · {a.category}</span><span>{a.maxMarks} marks · weight {a.weight}%</span></div>)}</div>}</section>
 {staff&&<section className={card}><h2 className="text-lg font-semibold">Link online written exams to the gradebook</h2><p className="text-sm text-muted-foreground">First create and assign a written exam in Organizations, then connect that assignment to a subject assessment. The exam total can differ from the gradebook total; moderation converts marks onto the assessment scale.</p>
 <div className="flex flex-wrap gap-2"><select aria-label="Academic assessment link" className={field} value={linkAssessment} onChange={e=>setLinkAssessment(e.target.value)}><option value="">Choose academic assessment</option>{assessments.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select><select aria-label="Written exam assignment link" className={field} value={linkAssignment} onChange={e=>setLinkAssignment(e.target.value)}><option value="">Choose assigned online exam</option>{linkedAssignments.map(a=><option value={a.id} key={a.id}>Assignment #{a.id} · Exam #{a.examId}</option>)}</select><button disabled={working||!linkAssessment||!linkAssignment} className={button} onClick={()=>action(()=>api(`/organizations/${org}/academic/assessments/${linkAssessment}/link-exam`,"POST",{assignmentId:Number(linkAssignment)}))}>Link exam</button></div>
 </section>}
 {staff&&<section className={card}><h2 className="text-lg font-semibold">AI marking moderation queue</h2><p className="text-sm text-muted-foreground">No AI result enters published academic reporting without educator approval. Review the learner's answer and rubric in the organisation submission console before accepting or changing the score.</p>
 {pending.length===0?<p className="text-sm text-muted-foreground">No linked exam submissions to review yet.</p>:<div className="space-y-2">{pending.map(p=><div key={p.attemptId} className="flex flex-wrap items-center justify-between gap-2 border-b pb-2 text-sm"><span>{p.assessmentTitle} · Learner {p.learnerId} · AI {p.awardedMarks}/{p.maxMarks} ({p.score}%) {p.reviewRequired?"· Flagged":""}</span>{p.reviewed?<span>Reviewed</span>:<button className="rounded-md border px-3 py-2" onClick={()=>{setSelectedAttempt(String(p.attemptId));setApprovedMarks(0);setReviewReason("")}}>Review and approve</button>}</div>)}</div>}
 {selectedAttempt&&<div className="space-y-3 rounded-lg border p-3"><p className="font-semibold">Review attempt #{selectedAttempt}</p><label className="block text-sm">Approved marks on the academic assessment scale <input className={field+" block"} type="number" min="0" value={approvedMarks} onChange={e=>setApprovedMarks(Number(e.target.value))}/></label><textarea className={field+" w-full"} rows={3} placeholder="Explain the mark and any moderation changes" aria-label="Moderation reason" value={reviewReason} onChange={e=>setReviewReason(e.target.value)}/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={publishApproved} onChange={e=>setPublishApproved(e.target.checked)}/> Publish approved result to learner reports</label><button disabled={working||reviewReason.trim().length<5} className={button} onClick={()=>action(async()=>{await api(`/organizations/${org}/academic/attempts/${selectedAttempt}/publish`,"POST",{marks:approvedMarks,reason:reviewReason,publish:publishApproved});setSelectedAttempt("")})}>Save moderated grade</button></div>}
 </section>}
 {staff&&<section className={card}><h2 className="text-lg font-semibold">Mark and publish learner results</h2><p className="text-sm text-muted-foreground">Learners must already be enrolled in the selected subject/module. Each change is recorded in an audit trail.</p><div className="grid gap-3 sm:grid-cols-3"><select aria-label="Select assessment to grade" className={field} value={gradeAssessment} onChange={e=>setGradeAssessment(e.target.value)}><option value="">Assessment</option>{assessments.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select><input aria-label="Learner account ID" placeholder="Enrolled learner ID" className={field} value={studentId} onChange={e=>setStudentId(e.target.value)}/><input aria-label="Awarded marks" type="number" min="0" className={field} value={score} onChange={e=>setScore(Number(e.target.value))}/></div><input className={field+" w-full"} aria-label="Marking reason" placeholder="Reason for mark entry or adjustment" value={reason} onChange={e=>setReason(e.target.value)}/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={publish} onChange={e=>setPublish(e.target.checked)}/> Publish reviewed result</label><button disabled={working||!gradeAssessment||!studentId||reason.trim().length<5} className={button} onClick={()=>action(()=>api(`/organizations/${org}/academic/assessments/${gradeAssessment}/grades/${encodeURIComponent(studentId)}`,"PUT",{marks:score,status:publish?"published":"draft",reason}))}>Save mark</button></section>}
 <section className={card}><h2 className="text-xl font-semibold">My performance report</h2>{!report?.results.length?<p className="text-sm text-muted-foreground">Published marks will appear here as your assessments are completed.</p>:<div className="overflow-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-2">Subject / module</th><th className="p-2">Period</th><th className="p-2">Progress</th><th className="p-2">Score</th></tr></thead><tbody>{report.results.map((r,i)=><tr className="border-t" key={i}><td className="p-2">{r.courseName}</td><td className="p-2">{r.periodName}</td><td className="p-2">{r.assessments} assessment(s)</td><td className="p-2">{r.percentage}% {r.provisional?"(partial)":""}</td></tr>)}</tbody></table></div>}</section>
 {staff&&<><section className={card}><h2 className="text-xl font-semibold">Institution reporting</h2><p className="text-3xl font-semibold">{staffReport?.averageScore==null?"—":staffReport.averageScore+"%"}</p><p className="text-sm text-muted-foreground">Mean of published learner/subject/period averages · {staffReport?.resultCount??0} reporting entries</p></section><section className={card}><h2 className="text-xl font-semibold">Top 10 learners</h2><p className="text-sm text-muted-foreground">Private to authorised educators. Rankings are scoped to the same course and term, based on published assessments only.</p><div className="flex flex-wrap gap-2"><select aria-label="Ranking course" className={field} value={courseId} onChange={e=>setCourseId(e.target.value)}><option value="">Select subject</option>{courses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select aria-label="Ranking period" className={field} value={periodId} onChange={e=>setPeriodId(e.target.value)}><option value="">Select period</option>{periods.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button disabled={!courseId||!periodId} className={button} onClick={()=>api<Leader[]>(`/organizations/${org}/academic/leaderboard?courseId=${courseId}&periodId=${periodId}`).then(setLeaders).catch(e=>setError(e.message))}>View top 10</button></div>{leaders.map(l=><div key={l.rank} className="flex justify-between border-b py-2 text-sm"><span>{l.rank}. {l.name}</span><span>{l.percentage}% {l.provisional?"· Partial":""}</span></div>)}</section></>}
 </>}
 </section>;
}