import {useEffect,useState} from "react";
type Opportunity={id:number;title:string;kind:string;description:string;organization:string};
type Application={id:number;opportunityId:number;status:string;createdAt:string};
type Evidence={id:number;instrumentName:string;provider:string;version:string;assessedAt:string;reviewDueAt:string;summary:string;verificationStatus:string};
const inp="w-full rounded-md border bg-background p-3 text-sm";
async function api<T>(url:string,body?:object):Promise<T>{const r=await fetch("/api"+url,{method:body?"POST":"GET",credentials:"include",headers:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});if(!r.ok){const d=await r.json().catch(()=>({}));throw Error(d.error??"Request failed")}return r.json()}
export default function CareerPassportPage(){
 const [jobs,J]=useState<Opportunity[]>([]),[applications,A]=useState<Application[]>([]),[evidence,E]=useState<Evidence[]>([]);
 const [chosen,C]=useState<number|null>(null),[statement,S]=useState(""),[instrument,I]=useState(""),[provider,P]=useState(""),[version,V]=useState("1"),[date,D]=useState(new Date().toISOString().slice(0,10)),[summary,SU]=useState("");
 const [busy,B]=useState(false),[error,ER]=useState(""),[success,OK]=useState("");
 const reload=async()=>{const [j,a,e]=await Promise.all([api<Opportunity[]>("/opportunities"),api<Application[]>("/opportunities/applications/me"),api<Evidence[]>("/passport/me")]);J(j);A(a);E(e)};
 useEffect(()=>{reload().catch(e=>ER(e.message))},[]);
 const run=async(fn:()=>Promise<unknown>,notice:string)=>{B(true);ER("");OK("");try{await fn();await reload();OK(notice)}catch(e){ER(e instanceof Error?e.message:"Action failed")}finally{B(false)}};
 return <section className="mx-auto max-w-6xl space-y-6 pb-16">
 <header className="space-y-2 border-b pb-5"><p className="text-xs uppercase tracking-widest text-muted-foreground">CABO Potential & Opportunity</p><h1 className="font-display text-3xl sm:text-4xl">Career opportunities & development passport</h1><p className="max-w-3xl text-muted-foreground">Apply for opportunities and privately record skills-development evidence. Self-entered items are never certified psychometric results and are not disclosed to employers by this page.</p></header>
 {error&&<p role="alert" className="rounded-md border border-destructive p-3">{error}</p>}{success&&<p role="status" className="rounded-md border p-3">{success}</p>}
 <div className="grid gap-5 lg:grid-cols-2">
  <section className="rounded-xl border p-5 space-y-4"><h2 className="font-display text-2xl">Discover opportunities</h2>{jobs.length===0?<p className="text-sm text-muted-foreground">No open opportunities yet.</p>:jobs.map(o=><article key={o.id} className="border-b pb-4 space-y-2"><p className="text-xs uppercase tracking-wide text-muted-foreground">{o.kind} · {o.organization}</p><h3 className="font-semibold">{o.title}</h3><p className="text-sm whitespace-pre-wrap">{o.description}</p><button className="rounded-md border px-3 py-2 text-sm" onClick={()=>C(o.id)}>Apply for this opportunity</button>{chosen===o.id&&<div className="space-y-2"><textarea className={inp} rows={4} value={statement} onChange={e=>S(e.target.value)} placeholder="Tell this organisation why you are interested and what relevant experience you bring" aria-label="Application statement"/><button className="rounded-md bg-primary px-4 py-2 text-sm text-primary-foreground disabled:opacity-50" disabled={busy||statement.trim().length<20} onClick={()=>run(async()=>{await api("/opportunities/"+o.id+"/applications",{statement});C(null);S("")},"Application submitted")}>Submit application</button></div>}</article>)}
  <h3 className="font-semibold">My submitted applications</h3>{applications.length===0?<p className="text-sm text-muted-foreground">You have not applied yet.</p>:applications.map(a=><p key={a.id} className="text-sm border-b py-2">Opportunity #{a.opportunityId} · {a.status}</p>)}</section>
  <section className="rounded-xl border p-5 space-y-4"><h2 className="font-display text-2xl">Private development passport</h2><p className="text-sm text-muted-foreground">Log learning and development evidence. CABO sets a six-month review reminder, not a mandatory psychometric retest.</p>
   {evidence.length===0?<p className="text-sm text-muted-foreground">No evidence recorded.</p>:evidence.map(e=><article key={e.id} className="border-b py-3"><p className="font-semibold">{e.instrumentName}</p><p className="text-xs text-muted-foreground">{e.provider} · {e.verificationStatus} · Review by {new Date(e.reviewDueAt).toLocaleDateString()}</p><p className="text-sm mt-1">{e.summary}</p></article>)}
   <div className="space-y-2 border-t pt-4"><h3 className="font-semibold">Add development evidence</h3><input className={inp} aria-label="Activity title" placeholder="Assessment or development activity title" value={instrument} onChange={e=>I(e.target.value)}/><input className={inp} aria-label="Activity provider" placeholder="School, provider or organiser" value={provider} onChange={e=>P(e.target.value)}/><div className="grid grid-cols-2 gap-2"><input className={inp} aria-label="Version" value={version} onChange={e=>V(e.target.value)}/><input className={inp} type="date" aria-label="Activity date" value={date} onChange={e=>D(e.target.value)}/></div><textarea className={inp} rows={3} aria-label="Development reflection" placeholder="What did you practise, demonstrate or learn?" value={summary} onChange={e=>SU(e.target.value)}/><button className="rounded-md bg-primary px-4 py-2 text-sm text-primary-foreground disabled:opacity-50" disabled={busy||instrument.length<3||provider.length<2} onClick={()=>run(async()=>{await api("/passport/development-evidence",{instrumentName:instrument,provider,version,assessedAt:new Date(date+"T12:00:00Z").toISOString(),summary});I("");SU("")},"Private development record added")}>Save evidence</button></div>
  </section>
 </div></section>
}
