import {useEffect,useState} from "react";
type Org={id:number;name:string;role:string};
type Enrolment={id:number;organizationId:number;organization:string;stage:string;academicYear:number;status:string};
type Transfer={id:number;toOrganizationId:number;fromOrganizationId:number;status:string;learnerId:string};
type Guardian={id:number;guardianId?:string;learnerId?:string;status:string};
const field="rounded-md border bg-background p-2 text-sm";
const btn="rounded-md bg-primary px-4 py-2 text-sm text-primary-foreground disabled:opacity-50";
async function api<T>(path:string,method="GET",body?:object):Promise<T>{const r=await fetch("/api"+path,{method,credentials:"include",headers:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});if(!r.ok){const x=await r.json().catch(()=>({}));throw Error(x.error||"Request failed")}return r.status===204?undefined as T:r.json()}
export default function InstitutionRecordsPage(){
 const [orgs,G]=useState<Org[]>([]),[enrollments,E]=useState<Enrolment[]>([]),[transfers,T]=useState<Transfer[]>([]),[guardians,GA]=useState<Guardian[]>([]),[incoming,IN]=useState<Guardian[]>([]),[staffTransfers,ST]=useState<Transfer[]>([]);
 const [org,O]=useState(""),[learner,L]=useState(""),[stage,S]=useState("RR"),[year,Y]=useState(new Date().getFullYear()),[enrollment,EN]=useState(""),[target,TA]=useState(""),[guardianEmail,GE]=useState("");
 const [error,ER]=useState(""),[message,M]=useState(""),[busy,B]=useState(false);
 const staff=orgs.filter(o=>["owner","admin"].includes(o.role));
 const reload=async()=>{const [mine,all,requests]=await Promise.all([api<{enrollments:Enrolment[];transfers:Transfer[];guardians:Guardian[]}>("/institution-records/me"),api<Org[]>("/organizations"),api<Guardian[]>("/guardian-relationships/incoming")]);E(mine.enrollments);T(mine.transfers);GA(mine.guardians);G(all);IN(requests)};
 useEffect(()=>{reload().catch(e=>ER(e.message))},[]);
 useEffect(()=>{if(!org){ST([]);return}api<Transfer[]>("/organizations/"+org+"/transfers/incoming").then(ST).catch(e=>ER(e.message))},[org]);
 const act=async(work:()=>Promise<unknown>,msg:string)=>{B(true);ER("");M("");try{await work();await reload();if(org&&staff.some(s=>String(s.id)===org))ST(await api("/organizations/"+org+"/transfers/incoming"));M(msg)}catch(e){ER(e instanceof Error?e.message:"Request failed")}finally{B(false)}};
 return <section className="mx-auto max-w-5xl space-y-6 pb-12">
  <header><p className="text-sm uppercase tracking-widest text-muted-foreground">CABO lifelong learner records</p><h1 className="text-3xl font-semibold">Institutions &amp; Guardians</h1><p className="text-muted-foreground">Institution-attested learning history, controlled transfer requests and guardian invitations. These are initial workflows, not nationally certified records or legally verified guardianship.</p></header>
  {error&&<p className="rounded-md border border-destructive p-3" role="alert">{error}</p>}
  {message&&<p className="rounded-md border p-3" role="status">{message}</p>}
  <section className="rounded-xl border p-5 space-y-3"><h2 className="text-xl font-semibold">My institution records</h2>{enrollments.length===0?<p className="text-sm text-muted-foreground">No institution-attested enrolments yet.</p>:enrollments.map(e=><div key={e.id} className="rounded-md border p-3"><p className="font-medium">{e.organization} · {e.academicYear}</p><p className="text-sm text-muted-foreground">{e.stage.match(/^\d+$|^R/)? "Grade "+e.stage:e.stage} · {e.status} · Institution recorded</p></div>)}
   <h3 className="font-semibold">Request school transfer</h3><p className="text-sm text-muted-foreground">Only you can request a transfer from your active record. Receiving schools must separately approve; no marks are transmitted.</p>
   <select className={field+" w-full"} aria-label="Active enrolment" value={enrollment} onChange={e=>EN(e.target.value)}><option value="">Select active enrolment</option>{enrollments.filter(e=>e.status==="active").map(e=><option key={e.id} value={e.id}>{e.organization} · {e.stage} · {e.academicYear}</option>)}</select>
   <select className={field+" w-full"} aria-label="Receiving institution" value={target} onChange={e=>TA(e.target.value)}><option value="">Select target organisation</option>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select>
   <button className={btn} disabled={busy||!enrollment||!target} onClick={()=>act(()=>api("/institution-records/transfers","POST",{fromEnrollmentId:Number(enrollment),toOrganizationId:Number(target)}),"Transfer requested")}>Request transfer</button>
   {transfers.map(t=><p className="border-b py-2 text-sm" key={t.id}>Transfer #{t.id} · To organisation #{t.toOrganizationId} · {t.status}</p>)}
  </section>
  <section className="rounded-xl border p-5 space-y-3"><h2 className="text-xl font-semibold">Guardian relationship requests</h2><p className="text-sm text-muted-foreground">These requests require acceptance but do not grant access to learning records. Legal guardian verification and controls for minors are still required.</p>
  <div className="flex flex-wrap gap-2"><input className={field+" flex-1"} type="email" placeholder="Existing guardian account email" aria-label="Guardian email" value={guardianEmail} onChange={e=>GE(e.target.value)}/><button className={btn} disabled={busy||!guardianEmail} onClick={()=>act(()=>api("/guardian-relationships","POST",{guardianEmail}),"Invitation created")}>Invite guardian</button></div>
  {guardians.map(g=><p key={g.id} className="text-sm">Guardian account {g.guardianId}: {g.status}</p>)}
  <h3 className="font-medium">Invitations received</h3>{incoming.length===0?<p className="text-sm text-muted-foreground">No incoming invitations</p>:incoming.map(g=><div key={g.id} className="flex flex-wrap items-center gap-2 border-b py-2 text-sm"><span className="flex-1">Learner account {g.learnerId} · {g.status}</span>{g.status==="pending"&&<><button className={btn} disabled={busy} onClick={()=>act(()=>api("/guardian-relationships/"+g.id+"/decision","POST",{decision:"accepted"}),"Relationship accepted without access permissions")}>Accept</button><button className="rounded-md border px-3 py-2" disabled={busy} onClick={()=>act(()=>api("/guardian-relationships/"+g.id+"/decision","POST",{decision:"declined"}),"Declined")}>Decline</button></>}</div>)}
  </section>
  {staff.length>0&&<section className="rounded-xl border p-5 space-y-3"><h2 className="text-xl font-semibold">Institution records desk</h2><p className="text-sm text-muted-foreground">For organisation owners/admins only. Check student identity and authority externally before attesting enrolment. This action does not issue an official certificate.</p>
  <select aria-label="Institution" className={field} value={org} onChange={e=>O(e.target.value)}><option value="">Choose institution</option>{staff.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select>
  <div className="grid gap-2 sm:grid-cols-3"><input aria-label="Learner account ID" className={field} placeholder="Learner account ID" value={learner} onChange={e=>L(e.target.value)}/><select className={field} value={stage} aria-label="Grade or stage" onChange={e=>S(e.target.value)}>{["RR","R",...Array.from({length:12},(_,i)=>String(i+1)),"university","college","training"].map(s=><option key={s} value={s}>{/^\d+$|^R/.test(s)?"Grade "+s:s}</option>)}</select><input className={field} aria-label="Academic year" type="number" value={year} onChange={e=>Y(Number(e.target.value))}/></div>
  <button className={btn} disabled={busy||!org||!learner} onClick={()=>act(()=>api("/organizations/"+org+"/verified-enrollments","POST",{learnerId:learner,stage,academicYear:year}),"Institution enrolment recorded")}>Record enrolment</button>
  <h3 className="font-semibold">Incoming transfers</h3>{staffTransfers.length===0?<p className="text-sm text-muted-foreground">No transfer requests</p>:staffTransfers.map(t=><div key={t.id} className="flex items-center gap-2 border-b py-2 text-sm flex-wrap"><span className="flex-1">Transfer #{t.id} · learner {t.learnerId} · {t.status}</span>{t.status==="pending"&&<><button className={btn} disabled={busy} onClick={()=>act(()=>api("/organizations/"+org+"/transfers/"+t.id+"/decision","POST",{decision:"accepted"}),"Transfer accepted without record disclosure")}>Accept</button><button className="rounded-md border px-3 py-2" disabled={busy} onClick={()=>act(()=>api("/organizations/"+org+"/transfers/"+t.id+"/decision","POST",{decision:"declined"}),"Transfer declined")}>Decline</button></>}</div>)}
  </section>}
 </section>
}