import {useEffect,useState} from "react";
type Entry={id:number;institutionName:string;stage:string;academicYear:number;note:string;source:string};
type Milestone={id:number;title:string;description:string;kind:string;year:number;source:string};
async function request<T>(path:string,method="GET",body?:object):Promise<T>{const r=await fetch("/api"+path,{method,credentials:"include",headers:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});if(!r.ok){const e=await r.json().catch(()=>({}));throw Error(e.error||"Request failed")}return r.status===204?undefined as T:r.json();}
const inp="rounded-md border bg-background p-2 text-sm";
const button="rounded-md bg-primary px-4 py-2 text-sm text-primary-foreground disabled:opacity-50";
export default function LearnerJourneyPage(){
 const [displayName,setName]=useState(""),[entries,setEntries]=useState<Entry[]>([]),[milestones,setMilestones]=useState<Milestone[]>([]);
 const [institution,setInstitution]=useState(""),[stage,setStage]=useState("RR"),[year,setYear]=useState(new Date().getFullYear()),[note,setNote]=useState("");
 const [title,setTitle]=useState(""),[description,setDescription]=useState(""),[kind,setKind]=useState("project");
 const [error,setError]=useState(""),[status,setStatus]=useState(""),[busy,setBusy]=useState(false);
 const reload=async()=>{const d=await request<{identity:{displayName:string};journeys:Entry[];milestones:Milestone[]}>("/learner-journey/me");setName(d.identity.displayName);setEntries(d.journeys);setMilestones(d.milestones)};
 useEffect(()=>{reload().catch(e=>setError(e.message))},[]);
 const action=async(fn:()=>Promise<unknown>,success:string)=>{setBusy(true);setStatus("");setError("");try{await fn();await reload();setStatus(success)}catch(e){setError(e instanceof Error?e.message:"Request failed")}finally{setBusy(false)}};
 return <section className="mx-auto max-w-5xl space-y-6 pb-12">
  <header><p className="text-sm uppercase tracking-widest text-muted-foreground">CABO lifelong development</p><h1 className="text-3xl font-semibold">My learning journey</h1><p className="text-muted-foreground">A continuous, private record of your learning history and milestones. Everything entered here is self-reported and not an officially verified school record.</p></header>
  {error&&<p className="rounded-md border border-destructive p-3" role="alert">{error}</p>}
  {status&&<p className="rounded-md border p-3" role="status">{status}</p>}
  <section className="rounded-xl border p-5 space-y-3"><h2 className="text-lg font-semibold">Learner identity</h2><label className="block text-sm">Preferred display name<input className={inp+" mt-1 w-full"} value={displayName} onChange={e=>setName(e.target.value)} maxLength={160}/></label><button className={button} disabled={busy} onClick={()=>action(()=>request("/learner-journey/me","PUT",{displayName}),"Identity saved")}>Save</button></section>
  <section className="rounded-xl border p-5 space-y-3"><h2 className="text-lg font-semibold">My education timeline</h2><div className="space-y-2">{entries.length===0&&<p className="text-sm text-muted-foreground">Add your first learning stage.</p>}{entries.map(e=><div className="flex justify-between gap-3 rounded-md border p-3" key={e.id}><div><p className="font-semibold">{e.academicYear} · {e.stage==="university"||e.stage==="college"||e.stage==="training"?e.stage:"Grade "+e.stage}</p><p className="text-sm">{e.institutionName}</p>{e.note&&<p className="text-sm text-muted-foreground">{e.note}</p>}<p className="text-xs text-muted-foreground">Self-reported</p></div><button disabled={busy} className="text-sm underline" onClick={()=>action(()=>request("/learner-journey/entries/"+e.id,"DELETE"),"Entry removed")}>Remove</button></div>)}</div>
  <div className="grid gap-2 sm:grid-cols-3"><input className={inp} aria-label="School or institution" placeholder="School or university name" value={institution} onChange={e=>setInstitution(e.target.value)}/><select className={inp} aria-label="Learning stage" value={stage} onChange={e=>setStage(e.target.value)}>{["RR","R",...Array.from({length:12},(_,i)=>String(i+1)),"university","college","training","professional"].map(s=><option key={s} value={s}>{["RR","R"].includes(s)||/^\d+$/.test(s)?"Grade "+s:s}</option>)}</select><input className={inp} type="number" aria-label="Year" value={year} onChange={e=>setYear(Number(e.target.value))}/></div><textarea className={inp+" w-full"} aria-label="Timeline note" placeholder="What changed or stood out at this stage?" value={note} onChange={e=>setNote(e.target.value)}/><button className={button} disabled={busy||institution.trim().length<2} onClick={()=>action(async()=>{await request("/learner-journey/entries","POST",{institutionName:institution,stage,academicYear:year,note});setNote("")},"Timeline entry added")}>Add learning stage</button></section>
  <section className="rounded-xl border p-5 space-y-3"><h2 className="text-lg font-semibold">Development milestones</h2>{milestones.map(m=><div key={m.id} className="flex justify-between gap-3 border-b py-3"><div><p className="font-semibold">{m.year} · {m.title}</p><p className="text-xs uppercase text-muted-foreground">{m.kind.replaceAll("_"," ")} · self-reported</p><p className="text-sm">{m.description}</p></div><button className="text-sm underline" disabled={busy} onClick={()=>action(()=>request("/learner-journey/milestones/"+m.id,"DELETE"),"Milestone removed")}>Remove</button></div>)}<div className="grid gap-2 sm:grid-cols-3"><input className={inp} placeholder="Milestone title" aria-label="Milestone title" value={title} onChange={e=>setTitle(e.target.value)}/><select className={inp} aria-label="Milestone type" value={kind} onChange={e=>setKind(e.target.value)}>{["academic","project","community","creative","technical","personal_growth","other"].map(k=><option key={k}>{k}</option>)}</select><input className={inp} aria-label="Milestone year" type="number" value={year} onChange={e=>setYear(Number(e.target.value))}/></div><textarea className={inp+" w-full"} rows={3} aria-label="Milestone description" value={description} onChange={e=>setDescription(e.target.value)} placeholder="Explain what you achieved, developed or learned"/><button className={button} disabled={busy||title.length<2||description.length<10} onClick={()=>action(async()=>{await request("/learner-journey/milestones","POST",{title,description,kind,year});setTitle("");setDescription("")},"Milestone added")}>Add milestone</button></section>
  <p className="text-sm text-muted-foreground">School enrolments, verified credentials, guardian permissions and school-to-school transfers will be added as separate controlled workflows. Your self-reported history is never automatically disclosed to employers.</p>
 </section>
}