import { useEffect, useState } from "react";
type Org={id:number;name:string;role:string};type Group={id:number;name:string};type Member={userId:string;email:string|null;role:string};type Exam={id:number;title:string};type Submission={id:number;userId:string;percentage:number;feedback:{questionIndex:number;awardedMarks:number;maxMarks:number;feedback:string}[]};
async function api<T>(path:string,body?:object):Promise<T>{const r=await fetch("/api"+path,{credentials:"include",method:body?"POST":"GET",headers:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.error||"Request failed");}return r.json();}
export default function OrganizationsPage(){
 const [orgs,S]=useState<Org[]>([]),[selected,O]=useState<number|null>(null),[name,N]=useState(""),[members,M]=useState<Member[]>([]),[groups,G]=useState<Group[]>([]),[exams,E]=useState<Exam[]>([]),[submissions,V]=useState<Submission[]>([]),[stats,D]=useState<Record<string,number|null>>({}),[error,F]=useState(""),[busy,B]=useState(false);
 const [email,EM]=useState(""),[role,R]=useState("learner"),[groupName,GN]=useState(""),[groupId,GI]=useState(""),[learnerId,LI]=useState(""),[examId,EI]=useState(""),[dueAt,DU]=useState("");
 const [reviewId,RI]=useState(""),[qIndex,QI]=useState(0),[marks,MA]=useState(0),[reason,RE]=useState("");
 const load=async()=>{const x=await api<Org[]>("/organizations");S(x);if(!selected&&x.length)O(x[0].id)};
 useEffect(()=>{load().catch(e=>F(e.message));api<Exam[]>("/written-exams").then(E).catch(()=>{});},[]);
 useEffect(()=>{if(!selected)return;Promise.all([api<Member[]>(`/organizations/${selected}/members`),api<Group[]>(`/organizations/${selected}/groups`),api<Record<string,number|null>>(`/organizations/${selected}/dashboard`),api<Submission[]>(`/organizations/${selected}/submissions`)]).then(([a,b,c,d])=>{M(a);G(b);D(c);V(d)}).catch(e=>F(e.message))},[selected]);
 async function run(action:()=>Promise<unknown>){B(true);F("");try{await action();await load();if(selected){const [a,b,c,d]=await Promise.all([api<Member[]>(`/organizations/${selected}/members`),api<Group[]>(`/organizations/${selected}/groups`),api<Record<string,number|null>>(`/organizations/${selected}/dashboard`),api<Submission[]>(`/organizations/${selected}/submissions`)]);M(a);G(b);D(c);V(d)}}catch(e){F(e instanceof Error?e.message:"Operation failed")}finally{B(false)}}
 const currentRole=orgs.find(o=>o.id===selected)?.role;
 const staff=Boolean(currentRole && ["owner","admin","teacher","assessor"].includes(currentRole));
 const canManageMembers=currentRole==="owner"||currentRole==="admin";
 const canSeeReviews=Boolean(currentRole && ["owner","admin","assessor"].includes(currentRole));
 return <section className="mx-auto max-w-5xl space-y-6 pb-12"><header><p className="text-sm uppercase tracking-widest text-muted-foreground">Training management</p><h1 className="text-3xl font-semibold">Organizations</h1><p className="text-muted-foreground">Company and classroom workspaces are optional. Your personal study space remains separate.</p></header>
 {error&&<div role="alert" className="rounded-lg border border-destructive p-3">{error}</div>}
 <section className="rounded-xl border p-5 space-y-3"><h2 className="font-semibold">Your workspaces</h2><div className="flex flex-wrap gap-2">{orgs.map(o=><button key={o.id} onClick={()=>O(o.id)} className="rounded-md border p-3" style={{fontWeight:selected===o.id?700:400}}>{o.name} · {o.role}</button>)}</div><div className="flex flex-wrap gap-2"><input aria-label="Organization name" className="rounded-md border bg-background p-2" placeholder="New company or school" value={name} onChange={e=>N(e.target.value)}/><button disabled={busy||!name.trim()} className="rounded-md bg-primary px-4 text-primary-foreground" onClick={()=>run(async()=>{const o=await api<{id:number}>("/organizations",{name});N("");O(o.id)})}>Create workspace</button></div></section>
 {selected&&<><div className="grid gap-3 sm:grid-cols-4">{[["Members",stats.members],["Groups",stats.groups],["Assignments",stats.assignments],["Submissions",stats.submissions]].map(([label,val])=><div className="rounded-xl border p-4" key={String(label)}><p className="text-sm text-muted-foreground">{label}</p><p className="text-3xl font-semibold">{val??"—"}</p></div>)}</div><p className="text-sm text-muted-foreground">Average AI score: {stats.averageAiScore==null?"No submissions yet":Number(stats.averageAiScore).toFixed(1)+"%"} · Provisional until assessor review</p>
 <section className="rounded-xl border p-5 space-y-3"><h2 className="text-lg font-semibold">People and access</h2>{members.map(m=><p key={m.userId} className="text-sm">{m.email||m.userId} — {m.role}</p>)}{canManageMembers&&<div className="flex flex-wrap gap-2"><input className="rounded-md border bg-background p-2" placeholder="Existing account email" aria-label="Member email" value={email} onChange={e=>EM(e.target.value)}/><select aria-label="Membership role" className="rounded-md border bg-background p-2" value={role} onChange={e=>R(e.target.value)}>{["learner","teacher","assessor",...(orgs.find(o=>o.id===selected)?.role==="owner"?["admin"]:[])].map(r=><option key={r}>{r}</option>)}</select><button disabled={busy} className="rounded-md border px-3" onClick={()=>run(()=>api(`/organizations/${selected}/members`,{email,role}))}>Add member</button></div>}</section>
 <section className="rounded-xl border p-5 space-y-3"><h2 className="text-lg font-semibold">Learner groups</h2>{groups.map(g=><p key={g.id} className="text-sm">{g.name} · #{g.id}</p>)}{staff&&<><div className="flex gap-2"><input aria-label="New group" className="rounded-md border bg-background p-2" placeholder="Group name" value={groupName} onChange={e=>GN(e.target.value)}/><button disabled={busy} className="rounded-md border px-3" onClick={()=>run(async()=>{await api(`/organizations/${selected}/groups`,{name:groupName});GN("")})}>Create group</button></div><div className="flex flex-wrap gap-2"><select className="rounded-md border bg-background p-2" aria-label="Learner group" value={groupId} onChange={e=>GI(e.target.value)}><option value="">Select group</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><select aria-label="Learner" className="rounded-md border bg-background p-2" value={learnerId} onChange={e=>LI(e.target.value)}><option value="">Select learner</option>{members.filter(m=>m.role==="learner").map(m=><option key={m.userId} value={m.userId}>{m.email||m.userId}</option>)}</select><button disabled={busy||!groupId||!learnerId} className="rounded-md border px-3" onClick={()=>run(()=>api(`/organizations/${selected}/groups/${groupId}/learners`,{userId:learnerId}))}>Add to group</button></div></>}</section>
 {staff&&<section className="rounded-xl border p-5 space-y-3"><h2 className="text-lg font-semibold">Assign written exam</h2><p className="text-sm text-muted-foreground">You can assign exams you created to your learner groups.</p><div className="flex flex-wrap gap-2"><select aria-label="Assignment group" className="rounded-md border bg-background p-2" value={groupId} onChange={e=>GI(e.target.value)}><option value="">Group</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><select aria-label="Written exam" className="rounded-md border bg-background p-2" value={examId} onChange={e=>EI(e.target.value)}><option value="">Exam</option>{exams.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select><input type="datetime-local" aria-label="Due date" value={dueAt} onChange={e=>DU(e.target.value)} className="rounded-md border bg-background p-2"/><button className="rounded-md bg-primary px-4 text-primary-foreground" disabled={busy||!groupId||!examId} onClick={()=>run(()=>api(`/organizations/${selected}/assignments`,{groupId:Number(groupId),examId:Number(examId),...(dueAt?{dueAt:new Date(dueAt).toISOString()}:{})}))}>Assign</button></div></section>}
 {canSeeReviews&&<section className="rounded-xl border p-5 space-y-3"><h2 className="text-lg font-semibold">Marking review</h2>{submissions.length===0?<p className="text-sm text-muted-foreground">No marked learner submissions yet.</p>:submissions.map(s=><div className="border-b pb-3" key={s.id}><button className="font-medium underline" onClick={()=>RI(String(s.id))}>Submission #{s.id} · Learner {s.userId} · AI {s.percentage}%</button>{reviewId===String(s.id)&&<div className="space-y-2 pt-2">{s.feedback.map(f=><p className="text-sm" key={f.questionIndex}>Q{f.questionIndex+1}: {f.awardedMarks}/{f.maxMarks} — {f.feedback}</p>)}<p className="text-sm text-muted-foreground">Overrides are recorded with the assessor and reason, without altering the original AI marks.</p><input type="number" min="0" aria-label="Question index (starts at zero)" className="w-28 rounded-md border bg-background p-2" value={qIndex} onChange={e=>QI(Number(e.target.value))}/><input type="number" min="0" step="0.5" aria-label="Awarded marks" className="w-28 rounded-md border bg-background p-2" value={marks} onChange={e=>MA(Number(e.target.value))}/><input className="rounded-md border bg-background p-2" aria-label="Review reason" placeholder="Reason for adjustment" value={reason} onChange={e=>RE(e.target.value)}/><button disabled={busy||reason.length<5} className="rounded-md border px-3" onClick={()=>run(()=>api(`/organizations/${selected}/submissions/${s.id}/overrides`,{questionIndex:qIndex,awardedMarks:marks,reason}))}>Record override</button></div>}</div>)}</section>}</>}
 </section>;
}